//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordServiceClient.XWordServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/XWordService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XWordServiceReference1.IDocPageFetchService")]
    public interface IDocPageFetchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPageFetchService/GetData", ReplyAction="http://tempuri.org/IDocPageFetchService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPageFetchService/GetData", ReplyAction="http://tempuri.org/IDocPageFetchService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPageFetchService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDocPageFetchService/GetDataUsingDataContractResponse")]
        XWordServiceClient.XWordServiceReference1.CompositeType GetDataUsingDataContract(XWordServiceClient.XWordServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPageFetchService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDocPageFetchService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<XWordServiceClient.XWordServiceReference1.CompositeType> GetDataUsingDataContractAsync(XWordServiceClient.XWordServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPageFetchService/GetDocPagesData", ReplyAction="http://tempuri.org/IDocPageFetchService/GetDocPagesDataResponse")]
        string GetDocPagesData(int docId, int startPageIdx, int endPageIdx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPageFetchService/GetDocPagesData", ReplyAction="http://tempuri.org/IDocPageFetchService/GetDocPagesDataResponse")]
        System.Threading.Tasks.Task<string> GetDocPagesDataAsync(int docId, int startPageIdx, int endPageIdx);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocPageFetchServiceChannel : XWordServiceClient.XWordServiceReference1.IDocPageFetchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocPageFetchServiceClient : System.ServiceModel.ClientBase<XWordServiceClient.XWordServiceReference1.IDocPageFetchService>, XWordServiceClient.XWordServiceReference1.IDocPageFetchService {
        
        public DocPageFetchServiceClient() {
        }
        
        public DocPageFetchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocPageFetchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocPageFetchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocPageFetchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public XWordServiceClient.XWordServiceReference1.CompositeType GetDataUsingDataContract(XWordServiceClient.XWordServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<XWordServiceClient.XWordServiceReference1.CompositeType> GetDataUsingDataContractAsync(XWordServiceClient.XWordServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetDocPagesData(int docId, int startPageIdx, int endPageIdx) {
            return base.Channel.GetDocPagesData(docId, startPageIdx, endPageIdx);
        }
        
        public System.Threading.Tasks.Task<string> GetDocPagesDataAsync(int docId, int startPageIdx, int endPageIdx) {
            return base.Channel.GetDocPagesDataAsync(docId, startPageIdx, endPageIdx);
        }
    }
}
